spring:
  datasource:
    url: jdbc:h2:mem:petsDB
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always