DROP TABLE IF EXISTS PETS;
CREATE TABLE PETS
(
    ID INTEGER not null primary key,
    NAME VARCHAR not null,
    BIRTHDAY DATE,
    OWNER_EMAIL VARCHAR not null
);

DROP TABLE IF EXISTS APPOINTMENTS;
CREATE TABLE APPOINTMENTS
(
    ID INTEGER not null primary key,
    PET_ID INTEGER not null,
    DESCRIPTION VARCHAR not null,
    START_DATE DATETIME,
    END_DATE DATETIME,
    ADDRESS VARCHAR,
    PRICE NUMERIC(10,2)
);

